language: java
if: tag IS present
install:
- true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jobs:
  include:
  - os: linux
    dist: bionic
    jdk: openjdk14
    addons:
      apt:
        packages:
          - fakeroot
    script: ./gradlew clean jpackage
    deploy:
      provider: releases
      token: $GITHUB_API_KEY
      file_glob: true
      file:
        - "build/jpackage/*.deb"
      skip_cleanup: true
      on:
        repo: dresch86/docxtobb-java
        tags: true
  - os: osx
    osx_image: xcode12
    jdk: openjdk14
    script: ./gradlew clean jpackage
    deploy:
      provider: releases
      token: $GITHUB_API_KEY
      file_glob: true
      file:
        - "build/jpackage/*.dmg"
        - "build/jpackage/*.pkg"
      skip_cleanup: true
      on:
        repo: dresch86/docxtobb-java
        tags: true
  - os: windows
    language: shell
    before_install:
      - powershell Install-WindowsFeature Net-Framework-Core
      - choco install openjdk --version=14.0.2
      - choco install gradle
      - choco install wixtoolset
    script: 
      - export GRADLE_OPTS="-Dorg.gradle.daemon=false $GRADLE_OPTS"
      - export JAVA_HOME="/c/Program Files/OpenJDK/jdk-14.0.2"
      - export PATH="$JAVA_HOME/bin:$PATH"
      - ./gradlew.bat clean jpackage
    deploy:
      provider: releases
      token: $GITHUB_API_KEY
      file_glob: true
      file:
        - "build/jpackage/*.exe"
        - "build/jpackage/*.msi"
      skip_cleanup: true
      on:
        repo: dresch86/docxtobb-java
        tags: true