/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ose.docxtobb;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testGUI() {
        App.launch(new String[]{});
    }
}
